name: Build Docker image

on:
  push:
    branches: main

permissions:
  contents: read
  packages: write

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check secret exists
        run: |
          if [ -z "${{ secrets.ORG_GHCR_TOKEN }}" ]; then
            echo "Secret is missing"
            exit 1
          else
            echo "Secret is available"
          fi

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ORG_GHCR_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/ksvdevops/ghcr-test:latest .

      - name: Push Docker image
        run: docker push ghcr.io/ksvdevops/ghcr-test:latest